name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar R
      uses: r-lib/actions/setup-r@v2

    - name: Instalar dependências do R
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Rodar R CMD check
      run: Rscript -e 'devtools::check()'
